
DROP TABLE IF EXISTS ADDRESSES CASCADE;

DROP TABLE IF EXISTS SERVISE_INFO CASCADE;

DROP TABLE IF EXISTS PRIVATE_INFORMATION CASCADE;

DROP TABLE IF EXISTS USER_TABLE CASCADE;

DROP TABLE IF EXISTS COLOR CASCADE;

DROP TABLE IF EXISTS CARDS;