INSERT INTO COLOR (color_name) VALUES('red') RETURNING id_color;

INSERT INTO COLOR (color_name) VALUES('yellow') RETURNING id_color;

INSERT INTO COLOR (color_name) VALUES('green') RETURNING id_color;

INSERT INTO COLOR (color_name) VALUES('blue') RETURNING id_color;



INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(0,1) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(1,1) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(1,1) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(2,1) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(2,1) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(3,1) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(3,1) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(4,1) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(4,1) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(5,1) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(5,1) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(6,1) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(6,1) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(7,1) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(7,1) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(8,1) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(8,1) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(9,1) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(9,1) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(0,2) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(1,2) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(1,2) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(2,2) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(2,2) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(3,2) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(3,2) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(4,2) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(4,2) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(5,2) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(5,2) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(6,2) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(6,2) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(7,2) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(7,2) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(8,2) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(8,2) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(9,2) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(9,2) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(0,3) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(1,3) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(1,3) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(2,3) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(2,3) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(3,3) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(3,3) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(4,3) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(4,3) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(5,3) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(5,3) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(6,3) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(6,3) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(7,3) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(7,3) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(8,3) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(8,3) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(9,3) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(9,3) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(0,4) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(1,4) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(1,4) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(2,4) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(2,4) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(3,4) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(3,4) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(4,4) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(4,4) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(5,4) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(5,4) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(6,4) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(6,4) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(7,4) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(7,4) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(8,4) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(8,4) RETURNING ID_CARD;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(9,4) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(9,4) RETURNING ID_CARD;



INSERT INTO COUNTRY (COUNTRY_NAME) VALUES('Russia') RETURNING ID_COUNTRY;

INSERT INTO COUNTRY (COUNTRY_NAME) VALUES('USA') RETURNING ID_COUNTRY;

INSERT INTO COUNTRY (COUNTRY_NAME) VALUES('France') RETURNING ID_COUNTRY;

INSERT INTO COUNTRY (COUNTRY_NAME) VALUES('China') RETURNING ID_COUNTRY;

INSERT INTO COUNTRY (COUNTRY_NAME) VALUES('India') RETURNING ID_COUNTRY;

INSERT INTO COUNTRY (COUNTRY_NAME) VALUES('Japan') RETURNING ID_COUNTRY;

INSERT INTO COUNTRY (COUNTRY_NAME) VALUES('UK') RETURNING ID_COUNTRY;

INSERT INTO COUNTRY (COUNTRY_NAME) VALUES('Spain') RETURNING ID_COUNTRY;

INSERT INTO COUNTRY (COUNTRY_NAME) VALUES('Canada') RETURNING ID_COUNTRY;

INSERT INTO COUNTRY (COUNTRY_NAME) VALUES('Italy') RETURNING ID_COUNTRY;



INSERT INTO CITY (CITY_NAME,ID_COUNTRY) VALUES('Samara',1) RETURNING ID_CITY;

INSERT INTO CITY (CITY_NAME,ID_COUNTRY) VALUES('Saint Petersburg',1) RETURNING ID_CITY;

INSERT INTO CITY (CITY_NAME,ID_COUNTRY) VALUES('Moscow',1) RETURNING ID_CITY;

INSERT INTO CITY (CITY_NAME,ID_COUNTRY) VALUES('NY',2) RETURNING ID_CITY;

INSERT INTO CITY (CITY_NAME,ID_COUNTRY) VALUES('London',7) RETURNING ID_CITY;

INSERT INTO CITY (CITY_NAME,ID_COUNTRY) VALUES('Beijing',4) RETURNING ID_CITY;
INSERT INTO CITY (CITY_NAME,ID_COUNTRY) VALUES('Osaka',6) RETURNING ID_CITY;

INSERT INTO CITY (CITY_NAME,ID_COUNTRY) VALUES('Paris',3) RETURNING ID_CITY;

INSERT INTO CITY (CITY_NAME,ID_COUNTRY) VALUES('Rome',10) RETURNING ID_CITY;

INSERT INTO CITY (CITY_NAME,ID_COUNTRY) VALUES('Madrid',8) RETURNING ID_CITY;


INSERT INTO SERVISE_INFO (LOGIN, PASSWORD, DATA_OF_REGISTRATION) VALUES('Team5','1q','2015-10-20');

INSERT INTO SERVISE_INFO (LOGIN, PASSWORD, DATA_OF_REGISTRATION) VALUES('Put',' ','2015-10-20');

INSERT INTO SERVISE_INFO (LOGIN, PASSWORD, DATA_OF_REGISTRATION) VALUES('Olga','1q','2015-10-20');

INSERT INTO SERVISE_INFO (LOGIN, PASSWORD, DATA_OF_REGISTRATION) VALUES('Anna','1q','2015-10-20');

INSERT INTO SERVISE_INFO (LOGIN, PASSWORD, DATA_OF_REGISTRATION) VALUES('Andrew','1q','2015-10-20');

INSERT INTO SERVISE_INFO (LOGIN, PASSWORD, DATA_OF_REGISTRATION) VALUES('Dmitriy','1q','2015-10-20');

INSERT INTO SERVISE_INFO (LOGIN, PASSWORD, DATA_OF_REGISTRATION) VALUES('Valentin','1q','2015-10-20');

INSERT INTO SERVISE_INFO (LOGIN, PASSWORD, DATA_OF_REGISTRATION) VALUES('Bob','1q','2015-10-20');

INSERT INTO SERVISE_INFO (LOGIN, PASSWORD, DATA_OF_REGISTRATION) VALUES('White','1q','2015-10-20');

INSERT INTO SERVISE_INFO (LOGIN, PASSWORD, DATA_OF_REGISTRATION) VALUES('Black','1q','2015-10-20');


INSERT INTO ADDRESSES (LOGIN, ID_CITY) VALUES('Team5', 1);

INSERT INTO ADDRESSES (LOGIN, ID_CITY) VALUES('Put', 3);
INSERT INTO ADDRESSES (LOGIN, ID_CITY) VALUES('Olga', 1);

INSERT INTO ADDRESSES (LOGIN, ID_CITY) VALUES('Anna', 1);

INSERT INTO ADDRESSES (LOGIN, ID_CITY) VALUES('Andrew', 1);
INSERT INTO ADDRESSES (LOGIN, ID_CITY) VALUES('Dmitriy', 1);

INSERT INTO ADDRESSES (LOGIN, ID_CITY) VALUES('Valentin', 1);

INSERT INTO ADDRESSES (LOGIN, ID_CITY) VALUES('Bob', 9);

INSERT INTO ADDRESSES (LOGIN, ID_CITY) VALUES('White', 4);

INSERT INTO ADDRESSES (LOGIN, ID_CITY) VALUES('Black', 5);


INSERT INTO PRIVATE_INFORMATION (LOGIN, NAME , SURNAME) VALUES('Team5','Team5','Team5');

INSERT INTO PRIVATE_INFORMATION (LOGIN, NAME , SURNAME) VALUES('Put','Vladimir','Put');

INSERT INTO PRIVATE_INFORMATION (LOGIN, NAME , SURNAME) VALUES('Olga','Olga','Mossoulina');

INSERT INTO PRIVATE_INFORMATION (LOGIN, NAME , SURNAME) VALUES('Anna','Anna','Tyumchenkova');

INSERT INTO PRIVATE_INFORMATION (LOGIN, NAME , SURNAME) VALUES('Andrew','Andrew','Lukyanov');

INSERT INTO PRIVATE_INFORMATION (LOGIN, NAME , SURNAME) VALUES('Dmitriy','Dmitriy','Kitaev');

INSERT INTO PRIVATE_INFORMATION (LOGIN, NAME , SURNAME) VALUES('Valentin','Valentin','Baranov');

INSERT INTO PRIVATE_INFORMATION (LOGIN, NAME , SURNAME) VALUES('Bob','Bob','Black');

INSERT INTO PRIVATE_INFORMATION (LOGIN, NAME , SURNAME) VALUES('White','Julia','White');

INSERT INTO PRIVATE_INFORMATION (LOGIN, NAME , SURNAME) VALUES('Black','Will','Smith');

