CREATE TABLE CARDS(
ID_CARD SERIAL NOT NULL,
ICON_ID INTEGER CHECK(ICON_ID =0 OR ICON_ID =1 OR ICON_ID =2 OR ICON_ID =3 OR ICON_ID =4 OR ICON_ID =5 OR ICON_ID =6 OR ICON_ID =7 OR ICON_ID =8 OR ICON_ID =9) NOT NULL,
ID_COLOR INTEGER,
PRIMARY KEY (ID_CARD)
);
ALTER TABLE CARDS ADD
  FOREIGN KEY (ID_COLOR) REFERENCES COLOR (ID_COLOR);
