CREATE TABLE USER_TABLE(
LOGIN CHAR(10) NOT NULL,
PRIMARY KEY (LOGIN)
);
ALTER TABLE USER_TABLE 
  ADD FOREIGN KEY (LOGIN) REFERENCES ADDRESSES (LOGIN);
ALTER TABLE USER_TABLE 
  ADD FOREIGN KEY (LOGIN) REFERENCES SERVISE_INFO (LOGIN);
ALTER TABLE USER_TABLE 
  ADD FOREIGN KEY (LOGIN) REFERENCES PRIVATE_INFORMATION (LOGIN);
