
CREATE TABLE COUNTRY(
ID_COUNTRY SERIAL NOT NULL,
COUNTRY_NAME CHAR(20),
PRIMARY KEY (ID_COUNTRY)
);


CREATE TABLE CITY(
ID_CITY SERIAL NOT NULL,
CITY_NAME CHAR(20),
ID_COUNTRY INTEGER,
PRIMARY KEY (ID_CITY)
);
ALTER TABLE CITY add
    FOREIGN KEY (ID_COUNTRY) REFERENCES COUNTRY (ID_COUNTRY);

CREATE TABLE USER_TABLE(
LOGIN CHAR(10) NOT NULL,
PRIMARY KEY (LOGIN)
);
ALTER TABLE USER_TABLE 
  ADD FOREIGN KEY (LOGIN) REFERENCES ADDRESSES (LOGIN);
ALTER TABLE USER_TABLE 
  ADD FOREIGN KEY (LOGIN) REFERENCES SERVISE_INFO (LOGIN);
ALTER TABLE USER_TABLE 
  ADD FOREIGN KEY (LOGIN) REFERENCES PRIVATE_INFORMATION (LOGIN);

CREATE TABLE ADDRESSES(
LOGIN CHAR(10),
ID_CITY INTEGER,
PRIMARY KEY (LOGIN)
);
ALTER TABLE ADDRESSES add
    FOREIGN KEY (ID_CITY) REFERENCES CITY (ID_CITY);

    
CREATE TABLE SERVISE_INFO(
LOGIN CHAR(10) NOT NULL,
PASSWORD CHAR(10) NOT NULL,
EMAIL CHAR(30) NOT NULL,
DATA_OF_REGISTRATION DATE NOT NULL,
PRIMARY KEY (LOGIN)
);

CREATE TABLE PRIVATE_INFORMATION(
LOGIN CHAR(10) NOT NULL,
NAME CHAR(20) NOT NULL,
SURNAME CHAR(20) NOT NULL,
PRIMARY KEY (LOGIN)
);



CREATE TABLE COLOR(
ID_COLOR SERIAL PRIMARY KEY ,
COLOR_NAME CHAR(10)
);


CREATE TABLE CARDS(
ID_CARD SERIAL NOT NULL,
ICON_ID INTEGER CHECK(ICON_ID =0 OR ICON_ID =1 OR ICON_ID =2 OR ICON_ID =3 OR ICON_ID =4 OR ICON_ID =5 OR ICON_ID =6 OR ICON_ID =7 OR ICON_ID =8 OR ICON_ID =9) NOT NULL,
ID_COLOR INTEGER,
PRIMARY KEY (ID_CARD)
);
ALTER TABLE CARDS ADD
  FOREIGN KEY (ID_COLOR) REFERENCES COLOR (ID_COLOR);
