CREATE TABLE PRIVATE_INFORMATION(
LOGIN CHAR(10) NOT NULL,
NAME CHAR(20) NOT NULL,
SURNAME CHAR(20) NOT NULL,
PRIMARY KEY (LOGIN)
);
ALTER TABLE PRIVATE_INFORMATION 
  ADD FOREIGN KEY (LOGIN) REFERENCES ADDRESSES (LOGIN);
ALTER TABLE PRIVATE_INFORMATION 
  ADD FOREIGN KEY (LOGIN) REFERENCES SERVISE_INFO (LOGIN)