INSERT INTO COLOR (color_name) VALUES('red') RETURNING id_color;
INSERT INTO COLOR (color_name) VALUES('yellow') RETURNING id_color;
INSERT INTO COLOR (color_name) VALUES('green') RETURNING id_color;
INSERT INTO COLOR (color_name) VALUES('blue') RETURNING id_color;


INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(0,1) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(1,1) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(1,1) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(2,1) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(2,1) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(3,1) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(3,1) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(4,1) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(4,1) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(5,1) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(5,1) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(6,1) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(6,1) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(7,1) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(7,1) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(8,1) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(8,1) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(9,1) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(9,1) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(0,2) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(1,2) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(1,2) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(2,2) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(2,2) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(3,2) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(3,2) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(4,2) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(4,2) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(5,2) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(5,2) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(6,2) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(6,2) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(7,2) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(7,2) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(8,2) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(8,2) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(9,2) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(9,2) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(0,3) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(1,3) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(1,3) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(2,3) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(2,3) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(3,3) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(3,3) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(4,3) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(4,3) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(5,3) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(5,3) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(6,3) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(6,3) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(7,3) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(7,3) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(8,3) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(8,3) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(9,3) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(9,3) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(0,4) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(1,4) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(1,4) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(2,4) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(2,4) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(3,4) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(3,4) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(4,4) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(4,4) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(5,4) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(5,4) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(6,4) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(6,4) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(7,4) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(7,4) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(8,4) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(8,4) RETURNING ID_CARD;

INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(9,4) RETURNING ID_CARD;
INSERT INTO CARDS (ICON_ID,ID_COLOR) VALUES(9,4) RETURNING ID_CARD;




INSERT INTO SERVISE_INFO (LOGIN, PASSWORD, EMAIL, DATA_OF_REGISTRATION) VALUES('Team5','1q','Team5@gmail.com','2015-10-20');
INSERT INTO SERVISE_INFO (LOGIN, PASSWORD, EMAIL, DATA_OF_REGISTRATION) VALUES('Put',' ','Put@gmail.com','2015-10-20');
INSERT INTO SERVISE_INFO (LOGIN, PASSWORD, EMAIL, DATA_OF_REGISTRATION) VALUES('Olga','1q','Team5Olga@gmail.com','2015-10-20');
INSERT INTO SERVISE_INFO (LOGIN, PASSWORD, EMAIL, DATA_OF_REGISTRATION) VALUES('Anna','1q','Team5Anna@gmail.com','2015-10-20');
INSERT INTO SERVISE_INFO (LOGIN, PASSWORD, EMAIL, DATA_OF_REGISTRATION) VALUES('Andrew','1q','Team5Andrew@gmail.com','2015-10-20');
INSERT INTO SERVISE_INFO (LOGIN, PASSWORD, EMAIL, DATA_OF_REGISTRATION) VALUES('Dmitriy','1q','Team5Dmitriy@gmail.com','2015-10-20');
INSERT INTO SERVISE_INFO (LOGIN, PASSWORD, EMAIL, DATA_OF_REGISTRATION) VALUES('Valentin','1q','Valentin@gmail.com','2015-10-20');
INSERT INTO SERVISE_INFO (LOGIN, PASSWORD, EMAIL, DATA_OF_REGISTRATION) VALUES('Bob','1q','Bob@gmail.com','2015-10-20');
INSERT INTO SERVISE_INFO (LOGIN, PASSWORD, EMAIL, DATA_OF_REGISTRATION) VALUES('White','1q','White@gmail.com','2015-10-20');
INSERT INTO SERVISE_INFO (LOGIN, PASSWORD, EMAIL, DATA_OF_REGISTRATION) VALUES('Black','1q','Black@gmail.com','2015-10-20');

INSERT INTO ADDRESSES (LOGIN, CITY, COUNTRY) VALUES('Team5', 'Samara', 'Russia');
INSERT INTO ADDRESSES (LOGIN, CITY, COUNTRY) VALUES('Put', 'Moscow', 'Russia');
INSERT INTO ADDRESSES (LOGIN, CITY, COUNTRY) VALUES('Olga', 'Samara', 'Russia');
INSERT INTO ADDRESSES (LOGIN, CITY, COUNTRY) VALUES('Anna', 'Samara', 'Russia');
INSERT INTO ADDRESSES (LOGIN, CITY, COUNTRY) VALUES('Andrew', 'Samara', 'Russia');
INSERT INTO ADDRESSES (LOGIN, CITY, COUNTRY) VALUES('Dmitriy', 'Samara', 'Russia');
INSERT INTO ADDRESSES (LOGIN, CITY, COUNTRY) VALUES('Valentin', 'Samara', 'Russia');
INSERT INTO ADDRESSES (LOGIN, CITY, COUNTRY) VALUES('Bob', 'London','UK');
INSERT INTO ADDRESSES (LOGIN, CITY, COUNTRY) VALUES('White', 'NY','USA');
INSERT INTO ADDRESSES (LOGIN, CITY, COUNTRY) VALUES('Black', 'London','UK');

INSERT INTO PRIVATE_INFORMATION (LOGIN, NAME , SURNAME, B_DATE) VALUES('Team5','Team5','Team5','2015-10-20');
INSERT INTO PRIVATE_INFORMATION (LOGIN, NAME , SURNAME, B_DATE) VALUES('Put','Vladimir','Put','2015-10-20');
INSERT INTO PRIVATE_INFORMATION (LOGIN, NAME , SURNAME, B_DATE) VALUES('Olga','Olga','Mossoulina','1995-7-12');
INSERT INTO PRIVATE_INFORMATION (LOGIN, NAME , SURNAME, B_DATE) VALUES('Anna','Anna','Tyumchenkova','2010-10-20');
INSERT INTO PRIVATE_INFORMATION (LOGIN, NAME , SURNAME, B_DATE) VALUES('Andrew','Andrew','Lukyanov','2012-10-20');
INSERT INTO PRIVATE_INFORMATION (LOGIN, NAME , SURNAME, B_DATE) VALUES('Dmitriy','Dmitriy','Kitaev','2011-10-20');
INSERT INTO PRIVATE_INFORMATION (LOGIN, NAME , SURNAME, B_DATE) VALUES('Valentin','Valentin','Baranov','2012-10-20');
INSERT INTO PRIVATE_INFORMATION (LOGIN, NAME , SURNAME, B_DATE) VALUES('Bob','Bob','Black','2014-10-20');
INSERT INTO PRIVATE_INFORMATION (LOGIN, NAME , SURNAME, B_DATE) VALUES('White','Julia','White','2012-10-20');
INSERT INTO PRIVATE_INFORMATION (LOGIN, NAME , SURNAME, B_DATE) VALUES('Black','Will','Smith','2011-10-20');

INSERT INTO USER_TABLE (LOGIN) VALUES('Team5');
INSERT INTO USER_TABLE (LOGIN) VALUES('Put');
INSERT INTO USER_TABLE (LOGIN) VALUES('Olga');
INSERT INTO USER_TABLE (LOGIN) VALUES('Anna');
INSERT INTO USER_TABLE (LOGIN) VALUES('Andrew');
INSERT INTO USER_TABLE (LOGIN) VALUES('Dmitriy');
INSERT INTO USER_TABLE (LOGIN) VALUES('Valentin');
INSERT INTO USER_TABLE (LOGIN) VALUES('Bob');
INSERT INTO USER_TABLE (LOGIN) VALUES('White');
INSERT INTO USER_TABLE (LOGIN) VALUES('Black');